### PR TITLE
Fixes #451: validate connectors

### LINKED ISSUE #451: Validate job connections on job submission
It doesn't appear that connections are tested when a job is submitted.  So if you fat finger a connection name you end up with failed slices.  It should be possible to validate all connections at job submission time.

### PR DESCRIPTION
**Pull request by erik-stephens**

### CODE REVIEW

File: spec/config/validators/config-spec.js [hunk 1]
```diff
@@ -41,3 +41,41 @@ describe('When passed a valid jobSchema and jobConfig', function() {
         expect(jobConfig).toEqual(validJob);
     });
 });
+
+describe('When passed a job without a known connector', function() {
```
Comment (godber) [inline spec/config/validators/config-spec.js]: I'd probably move this to it's own file: `spec/config/schemas/job-spec.js`.

I guess it's really a question of how to structure a unit test suite, and I think mirroring the code directory structure under `spec/` is a pretty straight forward way to do that.

Comment (erik-stephens) [inline spec/config/validators/config-spec.js]: On 2nd thought, I think the same spec file makes sense since I'm testing against validators/config.js and not validators/job.js.

Comment (godber) [inline spec/config/validators/config-spec.js]: Yeah, you're right.

**Comment by godber** [comment]
fixes #451

**Comment by kstaken** [comment]
Is this still WIP?

**Comment by erik-stephens** [comment]
No, I think just waiting for someone to bless it.
