### PR TITLE
cleaned up slicer and worker shutdown, fixed syntax error and error h…

### LINKED ISSUE #576: long running jobs get marked failed on the last slice
We've been running some id_reader jobs that run for about 24 hours and then get marked `failed` on the final slice when the job is completed. They're in `running` up to the end and there aren't any `error` slices so it seems to be some kind of issue that occurs as the job is finishing. Not entirely sure this is reader related but seems likely since the rest of the job is pretty normal stuff.

### PR DESCRIPTION
**Pull request by jsnoble**
…andling in job complete event resolves #576

### CODE REVIEW

**Comment by kstaken** [comment]
This needs a rebase

File: lib/cluster/slicer.js [hunk 1]
```diff
@@ -314,9 +313,14 @@ module.exports = function(context) {
                             }
 
                             messaging.send(msg);
+                        })
+                        .catch(function(err) {
+                            const errMsg = parseError(err);
+                            logger.error(`execution ${ex_id} was not able run the job complete sequence and update its status, slicer will soon exit, error: ${errMsg}`);
```
Comment (kstaken) [inline lib/cluster/slicer.js]: There's a typo in this message. "was not able run the job"

Would this be correct to say?

execution ${ex_id} has run to completion but the process has failed while updating the execution status, slicer will soon exit, error: ${errMsg}

**Comment by kstaken** [comment]
Integration and manual tests pass.
