### PR TITLE
fixed issues where a query with no results threw an error resolves #577

### LINKED ISSUE #577: elasticsearch slicer error
If a slicer when instantiating and determinng interval and range ran a query that returned no results, it would throw a formatting error. This needs to be able to be run and marked as completed.

### PR DESCRIPTION
**Pull request by jsnoble**

### CODE REVIEW

**Comment by kstaken** [comment]
Integration tests for this branch fail due to #579, rebasing to master allows tests to run.

**Comment by kstaken** [comment]
Integration tests pass on rebased branch.

**Comment by kstaken** [comment]
Manual test of a simple reindexing job with a query producing no results fails.

```
[2017-10-06T23:41:42.108Z] ERROR: teraslice/13867 on kteramac.local: [parse_exception] failed to parse date field [-0NaN--NaN--NaNT-NaN:-NaN:-NaN+00:00] with format [strict_date_optional_time||epoch_millis] (module=slicer, ex_id=fec9d01a-e9d4-4997-b438-2129080ff39d, job_id=4e90d98a-e2a0-44db-a003-7f96c200fc80)
[2017-10-06T23:41:42.110Z] ERROR: teraslice/13867 on kteramac.local: error with determine slice: [parse_exception] failed to parse date field [-0NaN--NaN--NaNT-NaN:-NaN:-NaN+00:00] with format [strict_date_optional_time||epoch_millis] (module=slicer, ex_id=fec9d01a-e9d4-4997-b438-2129080ff39d, job_id=4e90d98a-e2a0-44db-a003-7f96c200fc80)
[2017-10-06T23:41:42.112Z] ERROR: teraslice/13867 on kteramac.local: error while getting next slice [parse_exception] failed to parse date field [-0NaN--NaN--NaNT-NaN:-NaN:-NaN+00:00] with format [strict_date_optional_ti
```

File: integration-tests/spec/cases/data/reindex.js [hunk 1]
```diff
@@ -31,6 +32,33 @@ module.exports = function() {
...
+            teraslice.jobs.submit(job_spec)
+                .then(function(job) {
+                    expect(job).toBeDefined();
+                    expect(job.id()).toBeDefined();
+
+                    return job.waitForStatus('completed');
+                })
+                .then(function(status) {
+                    expect(status).toEqual('completed');
+                    return misc.indexStats('test-reindex-10')
```
Comment (kstaken) [inline integration-tests/spec/cases/data/reindex.js]: Shouldn't this be `test-reindex-bad-query`

**Comment by kstaken** [comment]
The manual test failure appears to be an intermittent issue. It failed the first time I ran it, then worked several times before failing again. Since then I haven't seen another failure in 30 runs.

**Comment by kstaken** [comment]
Submitted 50 jobs in a loop, all 50 completed so out of about 90 submissions 2 have failed.
