### PR TITLE
fixed bug when query returns no data resolves #392

### LINKED ISSUE #392: Exception when query doesn't return any results
The `query` parameter to elasticsearch_reader has an error if the query doesn't return any results.

```
Could not initialize slicers, error: TypeError: Cannot read property '_source' of undefined
        at /Users/kstaken/projects/opensource/teraslice/lib/readers/elasticsearch_date_range/slicer.js:119:86
        at bound (domain.js:287:14)
        at runBound (domain.js:300:12)
        at tryCatcher (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:507:31)
        at Promise._settlePromiseAt (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:581:18)
        at Promise._settlePromises (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/promise.js:697:14)
        at Async._drainQueue (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:123:16)
        at Async._drainQueues (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:133:10)
        at Immediate.Async.drainQueues [as _onImmediate] (/Users/kstaken/projects/opensource/teraslice/node_modules/bluebird/js/main/async.js:15:14)
        at processImmediate [as _immediateCallback] (timers.js:396:17)
```

### PR DESCRIPTION
**Pull request by jsnoble**

### CODE REVIEW

File: lib/readers/elasticsearch_date_range/slicer.js [hunk 1]
```diff
@@ -116,7 +116,7 @@ function newSlicer(context, opConfig, job, retryData, logger, client) {
         //using this query to catch potential errors even if a date is given already
         return elasticsearch.search(query)
             .then(function(results) {
-                var data = (results.hits && results.hits.hits) ? results.hits.hits[0]._source : results[0];
+                var data = (results.hits && results.hits.hits) ? _.get(results, "hits.hits[0]._source") : results[0];
```
Comment (erik-stephens) [inline lib/readers/elasticsearch_date_range/slicer.js]: I think this can be written without the checks:

    var data = _.get(results, 'hits.hits.0._source', results[0])

Playing around in the REPL:

```
> _.get({hits: {hits: []}}, 'hits.hits.0._source', 'NOPE')
'NOPE'
> _.get({hits: {hits: [{_source: 'YEEE'}]}}, 'hits.hits.0._source', 'NOPE')
'YEEE'
> _.get({}, 'hits.hits.0._source', 'NOPE')
'NOPE'
```

Comment (kstaken) [inline lib/readers/elasticsearch_date_range/slicer.js]: @jsnoble does @erik-stephens comment make sense?

**Comment by jsnoble** [comment]
made the code changes suggested
